language: haskell
install:
  - cabal install HUnit test-framework test-framework-hunit transformers-0.3.0.0
  - cabal configure --enable-test
  - cabal update && cabal install
notifications:
  email: true
