language: haskell
install:
  - cabal configure --enable-test
  - cabal update && cabal install
  - cabal install HUnit
  - cabal install test-framework
  - cabal install test-framework-hunit
notifications:
  email: true
